# Generated by Django 3.2.5 on 2021-07-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledState', models.BooleanField()),
                ('roomNumber', models.IntegerField()),
                ('lastToggle', models.DateField(auto_now=True)),
                ('lastUser', models.CharField(choices=[('OCCUPANT', 'OCCUPANT'), ('ADMIN', 'ADMIN')], max_length=10)),
            ],
        ),
    ]
